# Generated by Django 3.2.4 on 2021-07-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20210715_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.userinfo')),
            ],
            options={
                'db_table': 'PasswordReset',
            },
        ),
    ]
