# Generated by Django 3.2.4 on 2021-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20210729_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
