# Generated by Django 3.2.4 on 2021-07-07 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=20)),
                ('pro_price', models.FloatField(max_length=20)),
                ('pro_details', models.CharField(max_length=100)),
                ('pro_image', models.ImageField(upload_to='Images')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.categories')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
