# Generated by Django 3.2.4 on 2021-07-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='cat_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cat_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pro_details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pro_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pro_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pro_price',
            new_name='price',
        ),
    ]
