# Generated by Django 3.2.4 on 2021-07-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='brand',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
