# Generated by Django 3.2.4 on 2021-07-29 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_categories_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='brand',
        ),
    ]
