# Generated by Django 3.2.4 on 2021-07-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycart',
            old_name='cake',
            new_name='product',
        ),
    ]
