# Generated by Django 3.2.4 on 2021-07-21 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_product_brand'),
        ('Accounts', '0002_auto_20210715_0715'),
        ('UserApp', '0002_rename_cake_mycart_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.userinfo')),
            ],
            options={
                'db_table': 'CustBuild',
            },
        ),
    ]
