# Generated by Django 3.2.4 on 2021-07-21 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_product_brand'),
        ('UserApp', '0003_custbuild'),
    ]

    operations = [
        migrations.AddField(
            model_name='custbuild',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.categories'),
            preserve_default=False,
        ),
    ]
